### ISSUE TITLE
.htaccess file is publicly available on [byteball.org]

### ISSUE THREAD

**Issue by neutrinoguy** [byteball/byteball-web#49]
### Expected Behaviour

The htaccess file is used to stop users from accessing certain files and folders. It should not be available to anyone and should be hidden according to its RFC.

### Actual Behaviour

.htaccess file is available to anyone to view.

### Steps to Reproduce

1) Visit [https://byteball.org/.htaccess](https://byteball.org/.htaccess) in Browser and it will be downloaded which could be viewed in any text editor. 

or curl https://byteball.org/.htaccess will also work. 

### Possible Fix
Add below code to your htaccess file
`<files .htaccess>
order allow,deny
deny from all
</files>
` 

Thanks

**Comment by tonyofbyteball** [comment]
Thanks, good catch, it is fixed now.
